version: '3'
services:
  realworld-db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: dangerous
    ports:
      - 3306:3306
  # zookeeper:
  #   image: docker.io/bitnami/zookeeper:3.7
  #   ports:
  #     - "2181:2181"
  #   environment:
  #     - ALLOW_ANONYMOUS_LOGIN=yes    
  # kafka:
  #   image: docker.io/bitnami/kafka:2
  #   ports:
  #     - "9092:9092"
  #   environment:
  #     - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
  #     - ALLOW_PLAINTEXT_LISTENER=yes
  #   depends_on:
  #     - zookeeper
